### ISSUE TITLE
请问运行kbqa_test.py需要什么准备工作呢？

### ISSUE THREAD

**Issue by Ironeie** [WenRichard/KBQA-BERT#1]
我现在运行kbqa_test.py会提示很多文件找不到的错，有的是文件名不匹配，有的是压根不存在，从别的代码也没有找到可以生成这些文件的的地方，能否请您详细指导一下怎么跑通这个代码呢？谢谢。另外请问这个代码运行成功是相当于一个端到端的接口吗？就是我可以输入一个问题，直接输出一个答案给我

**Comment by WenRichard** [comment]
> 我现在运行kbqa_test.py会提示很多文件找不到的错，有的是文件名不匹配，有的是压根不存在，从别的代码也没有找到可以生成这些文件的的地方，能否请您详细指导一下怎么跑通这个代码呢？谢谢。另外请问这个代码运行成功是相当于一个端到端的接口吗？就是我可以输入一个问题，直接输出一个答案给我

首先要生成数据文件，您可以仔细看看文件的结构，现在的只是一个test，输入一些问题和答案，结果是测试准确率，您也可以稍加修改，就可以完成输入一个问题，输出一个答案
