### ISSUE TITLE
q_t_a_testing_predict.txt这个文件怎么生成的？

### ISSUE THREAD

**Issue by frankhetao** [WenRichard/KBQA-BERT#18]
执行python kbqa_test.py报错，Data/NER_Data/q_t_a_testing_predict.txt找不到，请问这个文件怎么生成的？谢谢

**Comment by pkuzhangyao** [comment]
terminal_predict.py中的outline模式生成吧，没记错的话

**Comment by frankhetao** [comment]
> terminal_predict.py中的outline模式生成吧，没记错的话

谢谢，自己看代码，看出来了

**Comment by nlpjoe** [comment]
#4

**Comment by GongFuXiong** [comment]
> terminal_predict.py中的outline模式生成吧，没记错的话

terminal_predict.py中的outline模式直接跑会出现，expected str, bytes or os.PathLike object, not NoneType，你们遇到了没

**Comment by Chaiyahui1998** [comment]
@GongFuXiong 我遇到你这个问题了，请问你解决了嘛

**Comment by Chaiyahui1998** [comment]
@frankhetao 请问我能加你QQ咨询你嘛
