### ISSUE TITLE
分享一个基于BERT的联合训练的思路

### ISSUE THREAD

**Issue by fyubang** [WenRichard/KBQA-BERT#25]
感谢作者的工作！

最近在做KBQA的百科问答，受作者项目的启发，开发了一个基于BERT联合训练的KBQA Demo。
https://github.com/fyubang/Joint-BERT-KBQA

**Comment by WenRichard** [comment]
> 感谢作者的工作！
> 
> 最近在做KBQA的百科问答，受作者项目的启发，开发了一个基于BERT联合训练的KBQA Demo。
> https://github.com/fyubang/Joint-BERT-KBQA

nice job！非常感谢您提供的思路！
