### ISSUE TITLE
你好，我下载了你的项目，但在运行run_ner的时候总是会卡在Saving checkpoint 0 to....这里，请问是什么原因呢？可不可以提供一下你训练好的模型呢？

### ISSUE THREAD

**Issue by amj0918150131** [WenRichard/KBQA-BERT#3]
你好，我下载了你的项目，但在运行run_ner的时候总是会卡在Saving checkpoint 0 to....这里，请问是什么原因呢？可不可以提供一下你训练好的模型呢？

**Comment by Ironeie** [comment]
我也遇到了这个问题，卡了很久之后提示OOM，即使把batch size设成1还是这样，感觉是GPU模式设置的问题。如果改成CPU运行就不会有这个问题。代码能力较渣还不知如何优化，如有解决方案还请提示一下，谢谢

**Comment by WONG-William** [comment]
大约需要15GB内存或者显存。

**Comment by zfz1015** [comment]
> 我也遇到了这个问题，卡了很久之后提示OOM，即使把batch size设成1还是这样，感觉是GPU模式设置的问题。如果改成CPU运行就不会有这个问题。代码能力较渣还不知如何优化，如有解决方案还请提示一下，谢谢

修改run_ner.sh的参数max_seq_length，改小点就好了

**Comment by WenRichard** [comment]
> 你好，我下载了你的项目，但在运行run_ner的时候总是会卡在Saving checkpoint 0 to....这里，请问是什么原因呢？可不可以提供一下你训练好的模型呢？

你好，ner部分是存在一些问题，我也没有解决，但是我没有遇到这种情况，可能很早的时候我是用cpu跑的，所以没碰到，很抱歉。

**Comment by WenRichard** [comment]
> 我也遇到了这个问题，卡了很久之后提示OOM，即使把batch size设成1还是这样，感觉是GPU模式设置的问题。如果改成CPU运行就不会有这个问题。代码能力较渣还不知如何优化，如有解决方案还请提示一下，谢谢

 zfz1015给出了解决方法，不知道现在还有这个问题嘛
