### ISSUE TITLE
运行kbqa_test.py时提示没有文件q_t_a_testing_predict.txt

### ISSUE THREAD

**Issue by Ironeie** [WenRichard/KBQA-BERT#4]
NER和SIM的模型都已经训练好了，最后一步运行kbqa_test.py时提示没有文件q_t_a_testing_predict.txt。我简单读了代码，似乎文件内容应该是question, entity, attribute, answer, ner的五元组，请问要如何获取这个文件呢？能否提供一个生成这个文件的脚本？

**Comment by WenRichard** [comment]
你说的没错，获取文件方法大概在terminal_predict.py的outline函数中

**Comment by Ironeie** [comment]
请问只能对已经提前完成命名实体识别的的语料做KBQA吗？比如我想线上输入一个问题，现场对这句话进行NER，生成SQL语句，然后做SIM，最后输出答案，这个有实现方法吗？

**Comment by WenRichard** [comment]
> 请问只能对已经提前完成命名实体识别的的语料做KBQA吗？比如我想线上输入一个问题，现场对这句话进行NER，生成SQL语句，然后做SIM，最后输出答案，这个有实现方法吗？

这个完全可以啊，线上对输入的自然语言句子进行NER，然后得出与NER出来的实体相关的N个实体，从数据库中查询实体对应的属性值，最后进行相似度计算就可以了啊。具体你可以参考README中的FAQ中的论文
