### ISSUE TITLE
运行run_ner.py时未找到dev.txt,请问这个文件是怎么生成的呢

### ISSUE THREAD

**Issue by rfjiangfdu** [WenRichard/KBQA-BERT#5]
Traceback (most recent call last):
  File "run_ner.py", line 865, in <module>
    tf.app.run()
  File "/home/rfjiangfdu/anaconda3/envs/python3.6/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_ner.py", line 700, in main
    eval_examples = processor.get_dev_examples(FLAGS.data_dir)
  File "run_ner.py", line 213, in get_dev_examples
    self._read_data(os.path.join(data_dir, "dev.txt")), "dev"
  File "run_ner.py", line 179, in _read_data
    with codecs.open(input_file, 'r', encoding='utf-8') as f:
  File "/home/rfjiangfdu/anaconda3/envs/python3.6/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: './Data/NER_Data/dev.txt

**Comment by WenRichard** [comment]
> Traceback (most recent call last):
> File "run_ner.py", line 865, in 
> tf.app.run()
> File "/home/rfjiangfdu/anaconda3/envs/python3.6/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
> _sys.exit(main(argv))
> File "run_ner.py", line 700, in main
> eval_examples = processor.get_dev_examples(FLAGS.data_dir)
> File "run_ner.py", line 213, in get_dev_examples
> self._read_data(os.path.join(data_dir, "dev.txt")), "dev"
> File "run_ner.py", line 179, in _read_data
> with codecs.open(input_file, 'r', encoding='utf-8') as f:
> File "/home/rfjiangfdu/anaconda3/envs/python3.6/lib/python3.6/codecs.py", line 897, in open
> file = builtins.open(filename, mode, buffering)
> FileNotFoundError: [Errno 2] No such file or directory: './Data/NER_Data/dev.txt

把生成的test.txt copy, 改成dev.txt
