### ISSUE TITLE
怎么多线程并行预测数据啊？

### ISSUE THREAD

**Issue by Little-girl-1992** [WenRichard/KBQA-BERT#6]
为什么你预测的输入和输出要使用队列和多线程，又设置Queue(maxsize=1)，这样不矛盾吗？

**Comment by WenRichard** [comment]
> 为什么你预测的输入和输出要使用队列和多线程，又设置Queue(maxsize=1)，这样不矛盾吗？

 estimator执行predict每次都会去加载图，用queue能避免这个问题
