### ISSUE TITLE
您好，想问下命名实体识别部分的问题

### ISSUE THREAD

**Issue by Ellie24678** [WenRichard/KBQA-BERT#7]
我想问下命名实体识别部分的主要运行哪个代码，命名实体的模型训练模型是哪个代码，代码能力比较差，希望能够得到回答，谢谢！

**Comment by WenRichard** [comment]
> 我想问下命名实体识别部分的主要运行哪个代码，命名实体的模型训练模型是哪个代码，代码能力比较差，希望能够得到回答，谢谢！

你好，可先耐心阅读代码和README文档
