### ISSUE TITLE
您好，想问一下报错的问题

### ISSUE THREAD

**Issue by yujh123** [WenRichard/KBQA-BERT#9]
absl.flags._exceptions.ValidationError: Flag --data_dir must have a value other than None.
absl.flags._exceptions.IllegalFlagValueError: flag --data_dir=None: Flag --data_dir must have a value other than None.
这两个错误是什么意思啊 不太懂 求指点

**Comment by WenRichard** [comment]
因为一开始没有生成数据集文件

**Comment by WenRichard** [comment]
> absl.flags._exceptions.ValidationError: Flag --data_dir must have a value other than None.
> absl.flags._exceptions.IllegalFlagValueError: flag --data_dir=None: Flag --data_dir must have a value other than None.
> 这两个错误是什么意思啊 不太懂 求指点

因为一开始没有生成数据集文件

**Comment by dongandi** [comment]
> absl.flags._exceptions.ValidationError: Flag --data_dir must have a value other than None.
> absl.flags._exceptions.IllegalFlagValueError: flag --data_dir=None: Flag --data_dir must have a value other than None.
> 这两个错误是什么意思啊 不太懂 求指点

请问你解决这个问题 了吗？ 我改了绝对路径，生成了文件还是不行
